### ISSUE TITLE
support chruby/ruby-install in addition to rbenv

### ISSUE THREAD

**Issue by thewoolleyman** [thoughtbot/laptop#355]
Hi,

I'd like to use chruby/ruby-install instead of rbenv.

I already have the changes working based on `USE_CHRUBY=true` env var being set.

Any interest in a pull request that supports this?  If so, I have some ideas to make this (and other optional environment choices) less hacky, which I can explain in more detail.

Thanks,
-- Chad

**Comment by croaky** [comment]
Hi @thewoolleyman. I think there's benefit to Laptop only having one Ruby switcher and one Ruby installer.

However, we've [been talking](https://github.com/thoughtbot/laptop/pull/324#issuecomment-64458322) about replacing ruby-build with ruby-install in order to take advantage of its anti-feature:

> Does not require updating every time a new Ruby version comes out.

We have a lot of people using ruby-build, though, and projects that have `.ruby-version` files that are designed for ruby-build.

Rubies installed by ruby-build are named with only their version number (e.g. 2.1.2), while rubies installed by ruby-install are named with the type of ruby and the version (e.g. ruby-2.1.2, jruby-2.1.2).

rbenv doesn't care what the versions are called...

```
$ rbenv versions
  system
  2.1.0
  2.1.5
* ruby-2.1.3 (set by /Users/grayson/.ruby-version)
  ruby-2.1.5
```

...until it tries to automatically switch versions based on a .ruby-version file.

To work, the .ruby-version file in every project would need to be changed to include the ruby- prefix. This change to the projects would be backwards-compatible with ruby-build rubies, but would display a warning:

`warning: ignoring extraneous `ruby-' prefix in version `ruby-2.1.0'`

We're currently experimenting with this shell function shim:

```
ruby-build() {
  ruby-install --install-dir "$HOME/.rbenv/versions/$1" ruby "$1"
}
```

**Comment by thewoolleyman** [comment]
OK, thanks for the response.  Makes sense that you want to keep the script focused.  I've already started going the route of writing a custom script, using some of your code as an example.  Probably easier that way.

Thanks for the response, anyway.

-- Chad

**Comment by croaky** [comment]
Sounds good. Thanks for opening the issue. It's always useful to hear which
tools people are using, and whether they might prefer them over the Laptop
defaults.
