### ISSUE TITLE
screen

### ISSUE THREAD

**Issue by cpyarger** [thoughtbot/laptop#367]
I would recommend installing GNU screen as when working in the terminal it makes for a very powerful tool. especially if you have to do any serial terminal work, or want to set up a multiPTY development environment.

**Comment by pbrisbin** [comment]
Though I do prefer screen, most thoughtbotters use tmux, which laptop does [install](https://github.com/thoughtbot/laptop/blob/master/mac#L142). I definitely don't think installing both is a good idea and I've yet to get my coworkers to switch. Thanks for the suggestion though, it's a great program.

**Comment by Keithbsmiley** [comment]
@pbrisbin probably isn't the best place for this conversation but why do you prefer screen? It seems like, before I started using tmux, most of the comparisons where just "tmux is a modern screen"

**Comment by pbrisbin** [comment]
I don't have any compelling reasons really. The two are so similar (except split support, which I'll mention below), that I think it makes the most sense to just use whichever you're used to. For me that's screen.

In my experience (extensive with screen, but limited with tmux), screen is less buggy. I don't seem to have any of the clipboard issues, or need reattach-to-userspace stuff (though that may be OSX, not tmux). I know screen well, and it's always Just Worked.

I use a tiling window manager, so my whole system basically works like tmux splits: when I want to "split" a terminal, I just open a new terminal window and my WM splits the workspace instead, placing the new terminal window in much the same way a tmux split would look. This works consistently with all applications -- it's pretty great. Therefore, I completely understand an OSX user preferring tmux because better split support* is important in a context where no good tiling WM exists.

*There's a 3rd party patch that adds tmux-like splitting to screen. I'd probably just move to tmux before dealing with that (minor but non-zero) headache.

**Comment by croaky** [comment]
I believe `screen` is also already installed on OS X by default.
