### ISSUE TITLE
Error fresh install - integer expression expected

### ISSUE THREAD

**Issue by chriskacerguis** [thoughtbot/laptop#377]
Seeing an error when doing a fresh install on Mac 10.10.3 (14D72i)
````
~ % sh mac 2>&1 | tee ~/laptop.log                                                   
mac: line 25: [: : integer expression expected
````

**Comment by Keithbsmiley** [comment]
I assume this is because this `1` should be wrapped in double quotes. But would like to hear from @thoughtbot/shell https://github.com/thoughtbot/laptop/blob/master/mac#L25

**Comment by mike-burns** [comment]
Using GNU Bash:

```bash
$ [ "1" -eq 1 ]
$ [ "" -eq 1 ]
bash: [: : integer expression expected
$ [ "x$foo" -eq "x1" ]
bash: [: x: integer expression expected
$ [ "x$foo" = "x1" ]
$ echo $?
1
$ foo=1
$ [ "x$foo" = "x1" ]
$ echo $?
0
```

**Comment by pbrisbin** [comment]
Yes, using `=` would be a more defensive approach. Since this is code we control (not user input), I think we can keep the assumption that our arguments are well-formed (that `$skip_new_line` is a number).

The real bug is [here](https://github.com/thoughtbot/laptop/blob/master/mac#L16). That should be:

```sh
local skip_new_line="${2:-0}"
```

**Comment by thiagogabriel** [comment]
Thanks @pbrisbin. Works like a charm :guitar:
