### ISSUE TITLE
permission denied when installing gems

### ISSUE THREAD

**Issue by acandael** [thoughtbot/laptop#380]
Hi,

I ran the Thoughtbot laptop script on my new iMac (Yosemite) with the commands

    curl --remote-name https://raw.githubusercontent.com/thoughtbot/laptop/master/mac
    less mac
    sh mac 2>&1 | tee ~/laptop.log

but when I try to install a gem, like

    gem install rails

I get the error

    ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /Users/acandael/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rails-4.2.0/README.md

The odd thing is, when I tried to create a new rail project the first time ( because I though the rails gem was installed), I got the suggestion to install rails as the sudo user:

    sudo gem install rails

so I did, but that also gives me permission errors

How can I fix this?

thanks for your help,

Anthony

**Comment by pbrisbin** [comment]
You should never `sudo gem install` things.

I'm not sure I can fully explain how you got into this situation -- it's possible that you attempted the `gem install` after having installed laptop, but before opening a new terminal. This would've given a permissions error since rbenv won't be activated until you open a fresh terminal. And it would've attempted to install the gem in the global location which is not usually user-writable.

The actual error you've pasted is not what I'd expect though. That error, I'd guess, may occur if you use `sudo gem install` after having activated rbenv. If that process wrote some things into `~/.rbenv/` as the root user, I'd expect the error you see on subsequent invocations of `gem install`.

I would suggest checking the permissions of the files under `~/.rbenv`. I don't know what they should be *exactly* (I'm a Linux user), but if they're owned by root or anything else odd like that, I would fix them (see `man chmod` and `man chown`). I would then confirm that `rbenv` is activated by invoking `gem env` and seeing that it will attempt to install into `~/.rbenv` and not some global directory.

Once these two things are done, `gem install rails` should work.

**Comment by acandael** [comment]
Hi pbrisbin, I found a solution on Stackoverflow: http://stackoverflow.com/questions/28846165/permission-error-when-trying-to-install-rails-osx

    sudo chown -R acandael ~/.rbenv

fixed the issue.

greetings,

Anthony

**Comment by pbrisbin** [comment]
Yup, that's what I would've expected the eventual fix to be.

> Your rbenv installation was incorrectly installed

I'm not sure how that happened, but I don't think it was laptop's fault. Feel free to re-open if you find evidence otherwise.
