### ISSUE TITLE
How can I uninstall everything?

### ISSUE THREAD

**Issue by NurdTurd** [thoughtbot/laptop#399]
How can I **uninstall** everything that was just installed on my system?

**Comment by AlJohri** [comment]
There's no easy way to uninstall "everything". Read through the script and reverse the steps. https://github.com/thoughtbot/laptop/blob/master/mac

This will uninstall a big chunk of the script as it removes all of Homebrew:
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#how-do-i-uninstall-homebrew

You'll need to revert your shell back to whatever it was before zsh (probably bash). Remove anything added to your ~/.zshrc file.

That should get you 95% of the way there.

**Comment by NurdTurd** [comment]
Thanks for the help.

**Comment by NurdTurd** [comment]
The reason I am asking is because I did a fresh reset and reinstall of my system. Ran the commands in the instructions. Now everytime I start my terminal I get this message: http://shel.io/f/CrMI.png

The `mtr` thing is me. But the other stuff I have no clue. Please help.

**Comment by Seralto** [comment]
Instead uninstall you can just run `exec bash -l` and get your bash back.

**Comment by NurdTurd** [comment]
Thanks @Seralto.

**Comment by MCodyB** [comment]
I'm not sure if the `exec bash -l` command would have given a different result, but I had to create `.bash_profile`, I copied the contents from `.zshrc`. Then since the terminal would go to my home dir every time I opened a new tab I had to change `$HOME/.bin` with `~/.rbenv/shims`

**Comment by derekprior** [comment]
Providing an automated uninstall would be difficult because we don't actually know what the start state of your machine is.

I would reverse the steps in the script somewhat manually:

1. `chsh /bin/bash` to switch back to bash
2. `rm -rf ~/.rbenv` to remove installed rubies/gems
3. `rm ~/..zshrc` to remove the zsh config we add (assumes you had no zsh config to start with)
4. [uninstall homebrew](https://docs.brew.sh/FAQ.html) (assumes homebrew was not installed to start with) or the individual formulas you want to remove.

... etc ...
