### ISSUE TITLE
reattach-to-user-namespace still necessary?

### ISSUE THREAD

**Issue by croaky** [thoughtbot/laptop#491]
@joshuaclayton @christoomey I saw some clipboard changes with a recent version of Tmux:

https://github.com/joshuaclayton/dotfiles/commit/3c852eab9540b5e56cdcedd0aff1a07db085c48a

Do y'all know if we can remove reattach-to-user-namespace from Laptop at this point?

**Comment by croaky** [comment]
Ah, looks like `reattach-to-user-namespace` is still used there.

What do those lines do, though? We don't have them in https://github.com/thoughtbot/dotfiles/blob/master/tmux.conf @geoffharcourt

**Comment by christoomey** [comment]
The changes to the `-T` variants are related to changes made to the key binding system in tmux 2.4 I believe. My understanding is the `reattach-to-user-namespace` is related to OS level stuff, so it would be independent from this change.

We'll likely need to update the dotfiles, although we'll need to support both 2.4+ syntax and older `bind -t` syntax. [This code block from tmux yank](https://github.com/tmux-plugins/tmux-yank/blob/e6e825186e306b6d0867d27e14ed0088d4faa97a/yank.tmux#L43-L63) has an example of how this could work.

**Comment by croaky** [comment]
I think I see: these lines are just for yanking from Vim into the clipboard?

```
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
```

So only necessary for folks using Vim inside Tmux who want to copy without using their mouse.

Installing `reattach-to-user-namespace` in Laptop as we have it allows for mouse copying inside Tmux.

**Comment by gohanlon** [comment]
Almost, @croaky. The two conf lines you listed above are to enable Tmux to copy to the system clipboard from within Tmux copy-mode (`prefix-[`): When in Tmux copy-mode, make pressing `Enter` pipe the selection (if any) to the command `reattach-to-user-namespace pbcopy` and cancel out of copy-mode.

As far as I know, `reattach-to-user-namespace` is (again) necessary as of macOS 10.12, but `reattach-to-user-namespace` won‘t do anything without being explicitly configured (and thoughtbot/dotfiles currently make no reference to it.)

In addition to the above conf for Tmux copy-mode, [my dotfiles](https://github.com/gohanlon/dotfiles-local/blob/master/tmux.conf.local) use the following to copy/paste from/to the macOS system clipboard from Tmux+Vim:

```
set -g default-command "reattach-to-user-namespace -l ${SHELL}"
```

I’m probably stating the obvious (especially to MacVim users!), but system clipboard integration is super useful. Using Vim motions and text objects instead of mousing selections is a win, and it‘s essential to me for multi-line copy (to avoid copying line numbers or adjacent splits/panes).

But, wow: thanks @christoomey for pointing out [tmux-yank](https://github.com/tmux-plugins/tmux-yank)! I recently spent way too much time getting Tmux+Vim and macOS system clipboard integration working, and the whole experience left me wanting for some canonical source that tracks this moving target—maybe the tmux-yank plugin is the answer.

**Comment by croaky** [comment]
Okay, thanks for the explanations everyone! Going to close this and leave `reattach-to-user-namespace` in Laptop. @geoffharcourt wonder if https://github.com/tmux-plugins/tmux-yank should be added to Dotfiles?

**Comment by geoffharcourt** [comment]
@croaky I like this idea!

**Comment by gohanlon** [comment]
I've had tmux-yank in my Dotfiles for about a month and am happy with it.

**Comment by stefanfrede** [comment]
There is this issue with sourcing via if-shell which at least for me is not solved: https://github.com/tmux-plugins/tpm/issues/59
