### ISSUE TITLE
cannot fork() for git-remote-https: Resource temporarily unavailable

### ISSUE THREAD

**Issue by acandael** [thoughtbot/laptop#526]
When I try to install laptop, I get this error message when installing Homebrew:

    ==> Downloading and installing Homebrew...
    error: cannot fork() for git-remote-https: Resource temporarily unavailable
    Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
    failed

I'm trying to install the script on MacOs High Sierra

thanks for your help,

Anthony

**Comment by acandael** [comment]
after installing Homebrew manually the laptop script seemed to run fine. The only thing I'm missing though is the 'tat' command to startup a tmux session.

**Comment by composerinteralia** [comment]
I'm going to close this, since it has been a couple years and it never got a response. 😢 

The `fork()` system call failing might have been an indication that there were [too many processes running](https://superuser.com/questions/441889/error-cannot-fork-for-status-resource-temporarily-unavailable-git). Rebooting might have helped. I don't think there is much we could have done within the laptop script to fix that. If I am wrong about that, we can reopen this issue.
