### ISSUE TITLE
Add Front-End Framework support?

### ISSUE THREAD

**Issue by co16353sidak** [thoughtbot/laptop#559]
Currently most developers have picked up a stack to work on, usually employing the use of a front-end framework such as that of React or Angular or Vue. These could be a good addition to this setup.

we could install npm packages or cli tools for whichever language a developer prefers or whatever is available, don't how to work on this per say but could be a good exploration option.

Any thoughts ?

**Comment by dknell** [comment]
We just use a custom `.laptop.local` file to customize our dev environments - like installing React, node, yarn, docker, IDEs, and other dependencies.

**Comment by composerinteralia** [comment]
Thanks for the issue! I agree with @dknell that `.laptop.local` is the correct place to add installs for project-specific things like front-end frameworks. We install ruby and nodejs, since we use those on a large number of projects at thoughtbot and all of us here are likely to need them at some point; but we don't install specific libraries or frameworks, since those vary widely from project to project.
