### ISSUE TITLE
openssl issues on macOS 10.15.2 + solution

### ISSUE THREAD

**Issue by sibsfinx** [thoughtbot/laptop#580]
Openssl and curl do not work after the installation (certificates problem):
```
curl: (77) error setting certificate verify locations:
  CAfile: /usr/local/etc/openssl/cert.pem
  CApath: none
```
for the following worked https://stackoverflow.com/a/54159644

**Comment by cpytel** [comment]
Thanks for creating this issue. I recognize you created it some time ago, thanks for your contributions and patience. I've merged in https://github.com/thoughtbot/laptop/pull/603 which drops official support for anything besides Monterey. 

I'm unable to test on a fresh install of any other versions at this time, and I assume you've since upgraded. But if you'd like to continue to work on this and it's still happening, let me know. Thanks again!
