### ISSUE TITLE
Warning: 'universal-ctags/universal-ctags/universal-ctags' formula is unreadable 

### ISSUE THREAD

**Issue by andyw8** [thoughtbot/laptop#611]
:wave: Running the script and I'm seeing this in the output:
```
Warning: 'universal-ctags/universal-ctags/universal-ctags' formula is unreadable: No available formula with the name "universal-ctags/universal-ctags/universal-ctags".
Please tap it and then try again: brew tap universal-ctags/universal-ctags
```
But it still seems to succeed since the next line shows:
```
Installing universal-ctags/universal-ctags/universal-ctags
```
MacOS 12.5 on a MacBook Air M2.

**Comment by cpytel** [comment]
Hi @andyw8

Yes, I can confirm I see the same on a fresh install of MacOS. Everything seems to be working properly, but we should try to add a tap and then install and see if it gets rid of the warning.

I don't have time to do this right now, which should be ok since everything is working and it doesn't seem urgent, but it would be good to do relatively soon. If someone else wants to try it, that'd be fine with me!

**Comment by cpytel** [comment]
I'm happy to finally resolve and close this issue! https://github.com/thoughtbot/laptop/pull/623
