### ISSUE TITLE
Installing `parity` has failed!

### ISSUE THREAD

**Issue by remy727** [thoughtbot/laptop#624]
<details>
  <summary>Show error</summary>

```shell
Installing parity
Warning: 'parity' formula is unreadable: No available formula with the name "parity". Did you mean pari?
Warning: No available formula with the name "parity". Did you mean pari?
==> Searching for similarly named formulae...
This similarly named formula was found:
pari
To install it, run:
  brew install pari
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
Installing parity has failed!
Using gh
Homebrew Bundle failed! 1 Brewfile dependency failed to install.
```
</details>

**Comment by cpytel** [comment]
Hi @remy727 I'm not able to replicate this. Here is a log from running the script on a fresh install of macOS Ventura 13.0.1.

[laptop.log](https://github.com/thoughtbot/laptop/files/10232660/laptop.log)

If possible, please provide the log and the macOS version you're running the script on and whether it is a fresh installation or not. Thanks.

**Comment by remy727** [comment]
Hi @cpytel, thank you for your reply.

I am on `macOS Monterey 12.6` and was going to install `parity `since it was new.
I disabled other commands except for parity and ran.

**Comment by cpytel** [comment]
Ok, thanks for the explanation. If you've "disabled other commands except for parity", then that means you've removed the command that means you've likely removed the tap command which tells Homebrew to include the actual parity location.

Instead of running the modified laptop script, it's best to just run:

```
brew tap thoughtbot/formulae
brew install parity
```

In your terminal.

I hope that helps. If you need further help with parity, it's probably best to go to https://github.com/thoughtbot/parity
